apiVersion: v1
kind: Service
metadata:
  name: studentdb
spec:
  ports:
  - port: 3306
  selector:
    app: studentdb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studentdb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: studentdb
spec:
  selector:
    matchLabels:
      app: studentdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: studentdb
    spec:
      containers:
      - image: mariadb
        name: studentdb
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: studentdb
        volumeMounts:
        - name: studentdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: studentdb-persistent-storage
        persistentVolumeClaim:
          claimName: studentdb-pv-claim
